services:
  handpose3d:
    tty: true
    stdin_open: true
    privileged: true
    network_mode: "host"   
    build:
      dockerfile: handpose3d.dockerfile
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ~/RPL/Software/handpose3d:/handpose3d
      - ~/RPL/Software/python_stereo_camera_calibrate:/python_stereo_camera_calibrate
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
#     networks:
#       - vm_network

# networks:
#   vm_network:
#     driver: macvlan
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.30.0.0/16
